
DEBUG = False
BUNDLE_ERRORS = True

SUPPORT_LANG_LIST = ['en_US', 'zh_Hans_CN']
DEFAULT_LANG = SUPPORT_LANG_LIST[0]

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2'
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:@127.0.0.1/web?charset=utf8'
SQLALCHEMY_TRACK_MODIFICATIONS = True
